# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       glib-networking

# >> macros
%define keepstatic 1
# << macros

Summary:    Network extensions for GLib
Version:    2.38.2
Release:    1
Group:      System/Libraries
License:    LGPLv2
URL:        http://git.gnome.org/browse/glib-networking/
Source0:    %{name}-%{version}.tar.xz
Source100:  glib-networking.yaml
BuildRequires:  pkgconfig(glib-2.0)
BuildRequires:  pkgconfig(gnutls)
BuildRequires:  intltool
BuildRequires:  ca-certificates

%description
Networking extensions for GLib

%prep
%setup -q -n %{name}-%{version}/glib-networking

# >> setup
# << setup

%build
# >> build pre
NOCONFIGURE=1 ./autogen.sh
# << build pre

%configure --disable-static
make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%find_lang glib-networking

%files -f glib-networking.lang
%defattr(-,root,root,-)
%{_libdir}/gio/modules/libgiognutls.so
# >> files
# << files
